module.exports = {
    project:"活动2",
    route:[{
        title:"第一页",
        data:{},
        name:"page1",
        param:["id"],
        components:[{
            component:"component1",
            npm:"jiayoubao_ui_component1",
            data:{
                name:"component1"
            }
        },{
            component:"component2",
            npm:"jiayoubao_ui_component2",
            version:"1.3.0",
            data:{
                name:"component2"
            }
        }]
    },{
        title:"第二页",
        data:{},
        name:"page2",
        components:[{
            component:"component1",
            npm:"jiayoubao_ui_component1",
            version:"1.2.0",
            data:{
                name:"component3"
            }
        },{
            component:"component2",
            npm:"jiayoubao_ui_component2",
            version:"1.3.0",
            data:{
                name:"component4"
            }
        }]
    }]
}
